---
title: "3 TP Ascidian Analysis"
author: "Shannon Eckhardt"
date: "2023-09-22"
output: html_document
---

# IMPORT LIBRARIES
```{r}
rm(list=ls())
library(tidyverse)
library(readxl)
library(openxlsx)
library(RColorBrewer)
```


# IMPORT ALL DATA
```{r}
full_data <- read_excel("/Users/Shannon/GitHub/NFI_benthic_community/3 TP Analysis/01 - Data/FULL_DATA_21_22_23.xlsx")
# interactions <- read_excel("Ascidian Data/Interactions.xlsx") DO THE INTERACTION DATA LATER BECAUSE IT NEEDS TO BE REDONE
```

# TRANSECT MEAN COVER
```{r}
transect.percent.cover <- full_data %>%
  group_by(TP, Site, Transect_ID, Category) %>%
  summarize(percent_cover = mean(sum_count)) %>% # mean() already gives a percentage
  mutate(SE = sd(percent_cover) / sqrt(n()))

site.percent.cover <- full_data %>%
  group_by(TP, Site, Category) %>%
  summarize(percent_cover = mean(sum_count)) %>% # mean() already gives a percentage
  mutate(SE = sd(percent_cover) / sqrt(n()))

tp.percent.cover <- full_data %>%
  group_by(Site, Category) %>%
  summarize(percent_cover = mean(sum_count)) %>% # mean() already gives a percentage
  mutate(SE = sd(percent_cover) / sqrt(n()))
```

# EXTRACT ASCIDIAN DATA
```{r}
# just the ascidians
ascd.transect.percent.cover <- transect.percent.cover[transect.percent.cover$Category == "Ascidians",]


# one df per site
SB_ascd_cover <- ascd.transect.percent.cover[ascd.transect.percent.cover$Site == "SB",]
EB_ascd_cover <- ascd.transect.percent.cover[ascd.transect.percent.cover$Site == "EB",]
CB_ascd_cover <- ascd.transect.percent.cover[ascd.transect.percent.cover$Site == "CB",]


#relevel sites, SB, EB, CB
ascd.transect.percent.cover$Site <- factor(ascd.transect.percent.cover$Site, levels = c("SB", "EB", "CB"))
```

# COVER PER SITE
```{r}
# pick site colors that match map in manuscript methods
site_colors <- c("CB" = "#FE7F9C", "EB" = "#EC9706", "SB" = "#52B2BF")

# SB: one outlier in 2023:
  # SB12 -> percent cover of 4.9%
  # removing from plot and then mention in figure legend "outlier in 2023 was removed with a value of 4.9%
#SB_ascd_cover <- subset(SB_ascd_cover, Transect_ID != "SB12")

SBcover <- ggplot(SB_ascd_cover, aes(x = TP, y = percent_cover, fill = Site)) +
  geom_boxplot(width = 0.3) +
  #stat_boxplot(geom = "errorbar", width = 0.3) +
  labs(x = "Time point", y = "Cover (%)") +
  scale_fill_manual(values = site_colors) +
  theme_classic() +
  #ylim(0,1) +
  theme(
    text = element_text(size = 16),  # Adjust the overall font size
    axis.text.x = element_text(size = 16),  # Adjust x-axis tick label font size
    axis.text.y = element_text(size = 16),  # Adjust y-axis tick label font size
    axis.title.x = element_text(size = 18),  # Adjust x-axis label font size
    axis.title.y = element_text(size =18),  # Adjust y-axis label font size
    legend.text = element_text(size = 16),  # Adjust legend text font size
    legend.title = element_text(size = 18),  # Adjust legend title font size
    legend.position = "bottom",  # Set legend position to bottom
    legend.justification = "center",  # Set legend justification to center
    legend.key.size = unit(1.2, "cm"))  # Adjust the size of the legend key

EBcover <- ggplot(EB_ascd_cover, aes(x = TP, y = percent_cover, fill = Site)) +
  geom_boxplot(width = 0.3) +
  #stat_boxplot(geom = "errorbar", width = 0.3) +
  labs(x = "Time point", y = "Cover (%)") +
  scale_fill_manual(values = site_colors) +
  theme_classic() +
  #ylim(0,1) +
  theme(
    text = element_text(size = 16),
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title.x = element_text(size = 18),
    axis.title.y = element_text(size =18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 18),
    legend.position = "bottom",
    legend.justification = "center",
    legend.key.size = unit(1.2, "cm"))

CBcover <- ggplot(CB_ascd_cover, aes(x = TP, y = percent_cover, fill = Site)) +
  geom_boxplot(width = 0.3) +
  #stat_boxplot(geom = "errorbar", width = 0.3) +
  labs(x = "Time point", y = "Cover (%)") +
  scale_fill_manual(values = site_colors) +
  theme_classic() +
  #ylim(0,5) +
  theme(
    text = element_text(size = 16),
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title.x = element_text(size = 18),
    axis.title.y = element_text(size =18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 18),
    legend.position = "bottom",
    legend.justification = "center",
    legend.key.size = unit(1.2, "cm"))

```
















